<?php

namespace App\Http\Controllers;

class WalletController extends Controller
{
    public function index()
    {
        $wallets = [
            // Main wallets
            ['name' => 'Ledger', 'logo' => '/static/logo/images.png', 'domain' => 'ledger.com'],
            ['name' => 'Wallet Connect', 'logo' => '/static/logo/walle.jpg', 'domain' => 'walletconnect.com'],
            ['name' => 'Metamask', 'logo' => '/static/logo/metamask.jpg', 'domain' => 'metamask.io'],
            ['name' => 'Binance Chain Wallet', 'logo' => '/static/logo/binance.png', 'domain' => 'binance.com'],
            ['name' => 'Xumm Wallet', 'logo' => '/static/logo/download-5.jpg', 'domain' => 'xumm.app'],
            ['name' => 'D\'Cent Wallet', 'logo' => '/static/logo/y-300x300.png', 'domain' => 'dcentwallet.com'],
            ['name' => 'Polygon Wallet', 'logo' => '/static/logo/polygon.jpg', 'domain' => 'polygon.technology'],
            ['name' => 'Bitpay', 'logo' => '/static/logo/bitpay.jpg', 'domain' => 'bitpay.com'],
            ['name' => 'Saita Pro', 'logo' => 'https://play-lh.googleusercontent.com/PD6ommpOAofmpJzNt5t4zDoGsloOi3O3EM8GoS0pGa6O5RAmRMvSD2CdY962LmaVwQ=s200', 'domain' => 'saitapro.com'],
            ['name' => 'Walleth', 'logo' => '/static/logo/walleth.jpg', 'domain' => 'walleth.org'],
            ['name' => 'SaitaMask', 'logo' => 'https://play-lh.googleusercontent.com/HmXjCZa048la55QfEg_6CJo8Qt7NN0HVUR2cu8uk5gm5BoNhEXulPrgT0Qbnoaf3tHfl', 'domain' => 'saitamask.org'],
            ['name' => 'Argent', 'logo' => '/static/logo/argent.jpg', 'domain' => 'argent.xyz'],
            ['name' => 'Encrypted Ink', 'logo' => '/static/logo/encrypted_ink.jpg', 'domain' => 'encrypted.ink'],
            ['name' => 'KEPLR', 'logo' => 'https://play-lh.googleusercontent.com/YM7h-nnxtDs9WROvE0GUzreNFua0eIm2N2m181BuiLgAqOeByqYZahsnbKos2xSGdAmv=w240-h480-rw', 'domain' => 'keplr.app'],
            ['name' => 'Plug Wallet', 'logo' => 'https://pbs.twimg.com/profile_images/1509949169909354503/eSuRl5Sk_400x400.jpg', 'domain' => 'plug.oo'],
            ['name' => 'Phantom', 'logo' => 'https://phantom.app/img/phantom-og.png', 'domain' => 'phantom.app'],
            ['name' => 'Compound', 'logo' => '/static/logo/compound.jpg', 'domain' => 'compound.finance'],
            ['name' => 'Iotex', 'logo' => '/static/logo/iotex.jpg', 'domain' => 'iotex.io'],
            ['name' => 'Coin98', 'logo' => '/static/logo/coin98.jpg', 'domain' => 'coin98.com'],
            ['name' => 'Coinbase', 'logo' => '/static/logo/coinbase.png', 'domain' => 'coinbase.com'],
            ['name' => 'Crypto.com | Defi Wallet', 'logo' => '/static/logo/crypto.jpg', 'domain' => 'crypto.com'],
            ['name' => 'Token Pocket', 'logo' => '/static/logo/token_pocket.jpg', 'domain' => 'tokenpocket.pro'],
            ['name' => 'Arculus', 'logo' => '/static/logo/Arculus.jpg', 'domain' => 'arculus.com'],
            ['name' => 'Math Wallet', 'logo' => '/static/logo/math_wallet.jpg', 'domain' => 'mathwallet.org'],
            ['name' => 'Ledger Live', 'logo' => '/static/logo/ledger_live.jpg', 'domain' => 'ledger.com'],
            ['name' => 'Dharma', 'logo' => '/static/logo/dharma.jpg', 'domain' => 'dharma.io'],
            ['name' => 'MYKEY', 'logo' => '/static/logo/mykey.jpg', 'domain' => 'mykey.org'],
            ['name' => 'Atomic', 'logo' => '/static/logo/atomic.jpg', 'domain' => 'atomicwallet.io'],
            ['name' => 'CoolWallet S', 'logo' => '/static/logo/cool_wallet_s.jpg', 'domain' => 'coolwallet.io'],
            ['name' => 'Nash', 'logo' => '/static/logo/nash.jpg', 'domain' => 'nash.io'],
            ['name' => 'Coinomi', 'logo' => '/static/logo/coinomi.jpg', 'domain' => 'coinomi.com'],
            ['name' => 'GridPlus', 'logo' => '/static/logo/gridplus.jpg', 'domain' => 'gridplus.io'],
            ['name' => 'Tokenary', 'logo' => '/static/logo/tokenary.jpg', 'domain' => 'tokenary.io'],
            ['name' => 'SafePal', 'logo' => '/static/logo/safepal.jpg', 'domain' => 'safepal.io'],
            ['name' => 'Infinito', 'logo' => '/static/logo/infinito.jpg', 'domain' => 'infinitowallet.io'],
            ['name' => 'Wallet.io', 'logo' => '/static/logo/wallet_io.jpg', 'domain' => 'wallet.io'],
            ['name' => 'Ownbit', 'logo' => '/static/logo/ownbit.jpg', 'domain' => 'ownbit.io'],
            ['name' => 'EasyPocket', 'logo' => '/static/logo/easypocket.jpg', 'domain' => 'easypocket.app'],
            ['name' => 'Bridge Wallet', 'logo' => '/static/logo/bridge_wallet.jpg', 'domain' => 'mtpelerin.com'],
            ['name' => 'BitKeep', 'logo' => '/static/logo/bitkeep.jpg', 'domain' => 'bitkeep.com'],
            ['name' => 'Unstoppable Wallet', 'logo' => '/static/logo/unstoppable_wallet.jpg', 'domain' => 'unstoppable.money'],
            ['name' => 'Ellipal Wallet', 'logo' => '/static/icon/logo/ellipal.jpeg', 'domain' => 'ellipal.com'],
            ['name' => 'HaloDefi Wallet', 'logo' => '/static/logo/halodefi_wallet.jpg', 'domain' => 'halodefi.org'],
            ['name' => 'Yoroi Wallet', 'logo' => 'https://play-lh.googleusercontent.com/UlhGKCVtUuXjDDF_fFdDQaF7mdUpMpsKvfQNNQHuwzbNEvvN-sYRNLk308wpWmLQkR4', 'domain' => 'yoroi.com'],
            ['name' => 'Dok Wallet', 'logo' => '/static/logo/dok_wallet.jpg', 'domain' => 'dokwallet.com'],
            ['name' => 'Cello Wallet', 'logo' => '/static/logo/celo_wallet.jpg', 'domain' => 'cellowallet.app'],
            ['name' => 'CoinUs', 'logo' => '/static/logo/coinus.jpg', 'domain' => 'coinus.io'],
            ['name' => 'Valora', 'logo' => '/static/logo/valora.jpg', 'domain' => 'valoraapp.com'],
            ['name' => 'Gaurda Wallet', 'logo' => '/static/logo/guarda_wallet.jpg', 'domain' => 'guarda.com'],
            ['name' => 'Jade Wallet', 'logo' => '/static/logo/jade_wallet.jpg', 'domain' => 'jadewallet.io'],
            ['name' => 'PlasmaPay', 'logo' => '/static/logo/plasmapay.jpg', 'domain' => 'plasmapay.com'],
            ['name' => 'O3Wallet', 'logo' => '/static/logo/o3_wallet.jpg', 'domain' => 'o3.network'],
            ['name' => 'HashKey Me', 'logo' => '/static/logo/hashkey_me.jpg', 'domain' => 'me.hashkey.com'],
            ['name' => 'RWallet', 'logo' => '/static/logo/rwallet.jpg', 'domain' => 'rsk.co'],
            ['name' => 'Flare Wallet', 'logo' => '/static/logo/flare_wallet.jpg', 'domain' => 'flarewallet.io'],
            ['name' => 'KyberSwap', 'logo' => '/static/logo/kyberswap.jpg', 'domain' => 'kyberswap.com'],
            ['name' => 'AToken Wallet', 'logo' => '/static/logo/atoken_wallet.jpg', 'domain' => 'atoken.com'],
            ['name' => 'Tongue Wallet', 'logo' => '/static/logo/tongue_wallet.jpg', 'domain' => 'tongue.fi'],
            ['name' => 'XinFin XDC Network', 'logo' => '/static/logo/xinfin.jpg', 'domain' => 'xinfin.io'],
            ['name' => 'Talken Wallet', 'logo' => '/static/logo/talken_wallet.jpg', 'domain' => 'talken.io'],
            ['name' => 'KEYRING PRO', 'logo' => '/static/logo/keyring_pro.jpg', 'domain' => 'keyring.app'],
            ['name' => 'Midas Wallet', 'logo' => '/static/logo/midas_wallet.jpg', 'domain' => 'midasprotocol.io'],
            ['name' => 'AT.Wallet', 'logo' => '/static/logo/at_wallet.jpg', 'domain' => 'authentrend.com'],
            ['name' => 'imToken', 'logo' => '/static/logo/imtoken.jpg', 'domain' => 'token.im'],
            ['name' => 'Trust Wallet', 'logo' => '/static/icon/logo/trustwallet-300x300.jpeg', 'domain' => 'trustwallet.com'],
            ['name' => 'Trezor Wallet', 'logo' => '/static/icon/logo/trezor-300x300.png', 'domain' => 'trezor.io'],
            ['name' => 'Exodus wallet', 'logo' => '/static/icon/logo/exodus.png', 'domain' => 'exodus.com'],
            ['name' => 'Bifrost', 'logo' => '/static/icon/logo/download-3.jpg', 'domain' => 'bifrost.finance'],
            ['name' => 'ZelCore', 'logo' => '/static/icon/logo/zel-300x300.jpeg', 'domain' => 'zelcore.io'],
            ['name' => 'XRP', 'logo' => '/static/icon/logo/download-3.jpg', 'domain' => 'xrp.org'],
            ['name' => 'Vision', 'logo' => '/static/icon/logo/vision-300x300.jpeg', 'domain' => 'vision.network'],
            ['name' => 'ViaWallet', 'logo' => '/static/icon/logo/via-300x300.jpeg', 'domain' => 'viawallet.com'],
            ['name' => 'Uphold', 'logo' => '/static/icon/logo/uphold-logo-vertical-color-big-1024x907-1-300x266.jpeg', 'domain' => 'uphold.com'],
            ['name' => 'Uniswap', 'logo' => '/static/icon/logo/0_u5_g8J6sa0IZYJtx-300x168.jpeg', 'domain' => 'uniswap.org'],
            ['name' => 'TrustVault', 'logo' => '/static/icon/logo/vault-300x300.jpeg', 'domain' => 'trustvault.io'],
            ['name' => 'Trustee Wallet', 'logo' => '/static/icon/logo/tee-300x300.jpeg', 'domain' => 'trustee.finance'],
            ['name' => 'Tradestation', 'logo' => '/static/icon/logo/Tradestation-300x300.png', 'domain' => 'tradestation.com'],
            ['name' => 'Torus', 'logo' => '/static/icon/logo/torus-300x300.jpeg', 'domain' => 'tor.us'],
            ['name' => 'TokenPocket', 'logo' => '/static/icon/logo/pocket-300x300.jpeg', 'domain' => 'tokenpocket.pro'],
            ['name' => 'Terra', 'logo' => '/static/icon/logo/download-13.png', 'domain' => 'terra.money'],
            ['name' => 'Spatium', 'logo' => '/static/icon/logo/spat-300x300.jpeg', 'domain' => 'spatium.net'],
            ['name' => 'SparkPoint', 'logo' => '/static/icon/logo/point-300x300.jpeg', 'domain' => 'sparkpoint.io'],
            ['name' => 'Solana Coin', 'logo' => '/static/icon/logo/download-11.jpg', 'domain' => 'solana.com'],
            ['name' => 'SHIBA INU', 'logo' => '/static/icon/logo/images-2.png', 'domain' => 'shibatoken.com'],
            ['name' => 'SecuX v20', 'logo' => '/static/icon/logo/secu-X-300x150.png', 'domain' => 'secux.io'],
            ['name' => 'Sandbox Token', 'logo' => '/static/icon/logo/download-6.jpg', 'domain' => 'sandbox.game'],
            ['name' => 'Safepal wallet', 'logo' => '/static/icon/logo/safepal.png', 'domain' => 'safepal.io'],
            ['name' => 'Rohinhood', 'logo' => '/static/icon/logo/Rohinhood.png', 'domain' => 'robinhood.com'],
            ['name' => 'Rainbow', 'logo' => '/static/icon/logo/rainbow-300x300.jpeg', 'domain' => 'rainbow.me'],
            ['name' => 'PoolTogether', 'logo' => '/static/icon/logo/601d5be7f1cf7d0eff03550e_PoolTogether500x500-300x300.png', 'domain' => 'pooltogether.com'],
            ['name' => 'Polygon (MATIC)', 'logo' => '/static/icon/logo/download-10.jpg', 'domain' => 'polygon.technology'],
            ['name' => 'Polkadot', 'logo' => '/static/icon/logo/download-14.png', 'domain' => 'polkadot.network'],
            ['name' => 'Pillar', 'logo' => '/static/icon/logo/pillar-300x300.jpeg', 'domain' => 'pillarproject.io'],
            ['name' => 'PEAKDEFI Wallet', 'logo' => '/static/icon/logo/peak-300x300.jpeg', 'domain' => 'peakdefi.com'],
            ['name' => 'Paybis', 'logo' => '/static/icon/logo/pay-300x137.jpg', 'domain' => 'paybis.com'],
            ['name' => 'ONTO', 'logo' => '/static/icon/logo/onto-300x300.jpeg', 'domain' => 'onto.app'],
            ['name' => 'Nuo', 'logo' => '/static/icon/logo/1553742453_Nuo-Network-Safe-Platform-to-Lend-Borrow-and-Trade-Cryptocurrency-Bitcoin-Exchange-Guide-300x194.jpeg', 'domain' => 'nuo.network'],
            ['name' => 'MyEtherWallet', 'logo' => '/static/icon/logo/ether.jpg', 'domain' => 'myetherwallet.com'],
            ['name' => 'MathWallet', 'logo' => '/static/icon/logo/math-300x300.jpeg', 'domain' => 'mathwallet.org'],
            ['name' => 'Maker', 'logo' => '/static/icon/logo/in-love-maker-coin-mascot-cartoon-vector-20118754-300x300.jpeg', 'domain' => 'makerdao.com'],
            ['name' => 'Loopring Wallet', 'logo' => '/static/icon/logo/loop-300x300.jpeg', 'domain' => 'loopring.io'],
            ['name' => 'Localbitcoin', 'logo' => '/static/icon/logo/Localbitcoin.png', 'domain' => 'localbitcoins.com'],
            ['name' => 'Kraken', 'logo' => '/static/icon/logo/Kraken-300x300.jpeg', 'domain' => 'kraken.com'],
            ['name' => 'Keepkey', 'logo' => '/static/icon/logo/keepkey.png', 'domain' => 'keepkey.com'],
            ['name' => 'Jaxx liberty wallet', 'logo' => '/static/icon/logo/jaxx.png', 'domain' => 'jaxx.io'],
            ['name' => 'IDEX', 'logo' => '/static/icon/logo/IdexLogo_Supplied_250x250.png', 'domain' => 'idex.io'],
            ['name' => 'ICON wallet', 'logo' => '/static/icon/logo/icon-wallet.png', 'domain' => 'icon.foundation'],
            ['name' => 'Huobi Wallet', 'logo' => '/static/icon/logo/hubi-300x300.jpeg', 'domain' => 'huobi.com'],
            ['name' => 'HEX', 'logo' => '/static/icon/logo/download-2.jpg', 'domain' => 'hex.com'],
            ['name' => 'Guarda Wallet', 'logo' => '/static/icon/logo/guard-300x300.jpeg', 'domain' => 'guarda.com'],
            ['name' => 'Gnosis Safe Multisig', 'logo' => '/static/icon/logo/gnoisis-300x300.jpeg', 'domain' => 'gnosis-safe.io'],
            ['name' => 'Gemini', 'logo' => '/static/icon/logo/Gemini.png', 'domain' => 'gemini.com'],
            ['name' => 'GateHub', 'logo' => '/static/icon/logo/GateHub.png', 'domain' => 'gatehub.net'],
            ['name' => 'Gate.io', 'logo' => '/static/icon/logo/gate-300x277.jpg', 'domain' => 'gate.io'],
            ['name' => 'Gala Token', 'logo' => '/static/icon/logo/download-12.png', 'domain' => 'gala.games'],
            ['name' => 'FTX', 'logo' => '/static/icon/logo/FTX-300x300.png', 'domain' => 'ftx.com'],
            ['name' => 'Fantom', 'logo' => '/static/icon/logo/download-4-300x150.jpg', 'domain' => 'fantom.foundation'],
            ['name' => 'Etoro', 'logo' => '/static/icon/logo/etoro-300x229.jpg', 'domain' => 'etoro.com'],
            ['name' => 'Enjin Wallet', 'logo' => '/static/icon/logo/Enjin-Wallet-300x271.jpeg', 'domain' => 'enjin.io'],
            ['name' => 'Eidoo', 'logo' => '/static/icon/logo/eidoo-300x300.jpeg', 'domain' => 'eidoo.io'],
            ['name' => 'dYdX', 'logo' => '/static/icon/logo/og-image-300x150.png', 'domain' => 'dydx.trade'],
            ['name' => 'Dexwallet', 'logo' => '/static/icon/logo/Dexwallet-300x300.jpeg', 'domain' => 'dexwallet.com'],
            ['name' => 'Defiant', 'logo' => '/static/icon/logo/defiant-300x300.jpeg', 'domain' => 'defiantapp.io'],
            ['name' => 'Cryptonator', 'logo' => '/static/icon/logo/Cryptonator-300x188.webp', 'domain' => 'cryptonator.com'],
            ['name' => 'Crypto Key Stack', 'logo' => '/static/icon/logo/Crypto-Key-Stack.png', 'domain' => 'cryptokeystack.com'],
            ['name' => 'CoolWallet', 'logo' => '/static/icon/logo/Coolwallet.png', 'domain' => 'coolwallet.io'],
            ['name' => 'Coinmama', 'logo' => '/static/icon/logo/mama-300x220.jpg', 'domain' => 'coinmama.com'],
            ['name' => 'Coinify', 'logo' => '/static/icon/logo/Coinify.jpeg', 'domain' => 'coinify.com'],
            ['name' => 'BitKeep Wallet', 'logo' => '/static/icon/logo/keep-300x300.jpeg', 'domain' => 'bitkeep.com'],
            ['name' => 'Binance Chain', 'logo' => '/static/icon/logo/chain-300x300.jpg', 'domain' => 'binance.org'],
            ['name' => 'Authereum', 'logo' => '/static/icon/logo/auther-300x300.jpeg', 'domain' => 'authereum.com'],
            ['name' => 'AlphaWallet', 'logo' => '/static/icon/logo/alpha-300x300.jpeg', 'domain' => 'alphawallet.com'],
            ['name' => 'Alice', 'logo' => '/static/icon/logo/alice-300x300.jpeg', 'domain' => 'alice.app'],
            ['name' => 'Aladdin Wallet', 'logo' => '/static/icon/logo/Aladdin-Wallet.png', 'domain' => 'aladdincrypto.com'],
            ['name' => 'Aktionariat', 'logo' => '/static/icon/logo/aktio-300x300.jpeg', 'domain' => 'aktionariat.com'],
            ['name' => 'Airswap', 'logo' => '/static/icon/logo/airswap-pr-300x200.jpeg', 'domain' => 'airswap.io'],
            ['name' => 'Airgap', 'logo' => '/static/icon/logo/Airgap-300x290.jpeg', 'domain' => 'airgap.it'],
            ['name' => '1inch Wallet', 'logo' => '/static/icon/logo/inch-300x300.jpeg', 'domain' => '1inch.io'],
            ['name' => 'Tangem Wallet', 'logo' => '/static/icon/logo/tangem.png', 'domain' => 'tangem.com'],
            ['name' => 'Nexo Wallet', 'logo' => '/static/icon/logo/nexo.png', 'domain' => 'nexo.io'],
            ['name' => '0x', 'logo' => '/static/icon/logo/0x-300x200.jpeg', 'domain' => '0x.org'],
        ];

        return view('connect.index', ['wallets' => $wallets]);
    }

    public function connect()
    {
        return response()->json([
            'status' => 'success',
            'message' => 'Wallet connected successfully'
        ]);
    }
}
